#!/bin/sh

docker run --detach --name vespa --hostname vespa-container --privileged --volume /Users/philipp/Desktop/code.nosync/vespa-quickstart/vespa-sample-apps:/vespa-sample-apps --publish 8080:8080 vespaengine/vespa
